Repository mwvgroup/pittgoogle-client, pull requests merged in 2025-03, with the labels that each got.

#73 Bugfixes for GitHub Actions
  .github/workflows/PackageTest.yml
  docs/source/for-developers/build-docs-sphinx.md
  docs/source/for-developers/manage-dependencies-poetry.md
  docs/source/for-developers/setup-environment.md
  pittgoogle/__init__.py
  pittgoogle/alert.py
  pittgoogle/pubsub.py
  pittgoogle/registry.py
  pittgoogle/schema.py
  pittgoogle/types_.py
  poetry.lock
  pyproject.toml
  tests/test_placeholder.py
  tests/test_registry.py
Labels: bug, dependencies

#70 Update LSST schemas for v7
  CHANGELOG.md
  pittgoogle/registry_manifests/schemas.yml
  pittgoogle/schema.py
  pittgoogle/schemas/lsst/7/2/lsst.v7_2.alert.avsc
  pittgoogle/schemas/lsst/7/2/lsst.v7_2.diaForcedSource.avsc
  pittgoogle/schemas/lsst/7/2/lsst.v7_2.diaNondetectionLimit.avsc
  pittgoogle/schemas/lsst/7/2/lsst.v7_2.diaObject.avsc
  pittgoogle/schemas/lsst/7/2/lsst.v7_2.diaSource.avsc
  pittgoogle/schemas/lsst/7/2/lsst.v7_2.ssObject.avsc
  pittgoogle/schemas/lsst/7/3/lsst.v7_3.alert.avsc
  pittgoogle/schemas/lsst/7/3/lsst.v7_3.diaForcedSource.avsc
  pittgoogle/schemas/lsst/7/3/lsst.v7_3.diaNondetectionLimit.avsc
  pittgoogle/schemas/lsst/7/3/lsst.v7_3.diaObject.avsc
  pittgoogle/schemas/lsst/7/3/lsst.v7_3.diaSource.avsc
  pittgoogle/schemas/lsst/7/3/lsst.v7_3.ssObject.avsc
  pittgoogle/schemas/lsst/7/4/lsst.v7_4.alert.avsc
  pittgoogle/schemas/lsst/7/4/lsst.v7_4.diaForcedSource.avsc
  pittgoogle/schemas/lsst/7/4/lsst.v7_4.diaNondetectionLimit.avsc
  pittgoogle/schemas/lsst/7/4/lsst.v7_4.diaObject.avsc
  pittgoogle/schemas/lsst/7/4/lsst.v7_4.diaSource.avsc
  pittgoogle/schemas/lsst/7/4/lsst.v7_4.ssObject.avsc
  tests/conftest.py
  tests/data/sample_alerts/lsst/README.md
  tests/data/sample_alerts/lsst/lsst.v7_0.avro
  tests/data/sample_alerts/lsst/lsst.v7_2.avro
  tests/data/sample_alerts/lsst/lsst.v7_3.avro
  tests/data/sample_alerts/lsst/lsst.v7_4.avro
  tests/test_registry.py
Labels: enhancement

#67 Add support for LVK and Cloud Functions
  CHANGELOG.md
  docs/source/for-developers/setup-environment.md
  pittgoogle/alert.py
  pittgoogle/pubsub.py
  pittgoogle/registry_manifests/schemas.yml
  pittgoogle/schemas/maps/TEMPLATE.yml
  pittgoogle/schemas/maps/elasticc.yml
  pittgoogle/schemas/maps/lsst.yml
  pittgoogle/schemas/maps/lvk.yml
  pittgoogle/schemas/maps/ztf.yml
  pittgoogle/types_.py
  pittgoogle/utils.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/data/sample_alerts/lvk/MS181101ab-earlywarning.json
  tests/data/sample_alerts/lvk/MS181101ab-ext-update.json
  tests/data/sample_alerts/lvk/MS181101ab-initial.json
  tests/data/sample_alerts/lvk/MS181101ab-preliminary.json
  tests/data/sample_alerts/lvk/MS181101ab-retraction.json
  tests/data/sample_alerts/lvk/MS181101ab-update.json
  tests/data/sample_alerts/lvk/README.md
  tests/test_alert.py
  tests/test_utils.py
Labels: enhancement

#75 Update Data Listings
  CHANGELOG.md
  docs/source/listings.rst
  docs/source/surveys/index.rst
  docs/source/surveys/lsst.rst
Labels: documentation

#81 Consolidate LSST schemas and enhance `Alert` for Pitt-Google-Broker/pull/263
  CHANGELOG.md
  pittgoogle/alert.py
  pittgoogle/exceptions.py
  pittgoogle/registry.py
  pittgoogle/registry_manifests/schemas.yml
  pittgoogle/schema.py
  pittgoogle/schemas/maps/TEMPLATE.yml
  pittgoogle/schemas/maps/default.yml
  tests/conftest.py
  tests/data/sample_alerts/lsst/lsst.v7_0.avro
  tests/data/sample_alerts/lsst/lsst.v7_1.avro
  tests/data/sample_alerts/lsst/lsst.v7_2.avro
  tests/data/sample_alerts/lsst/lsst.v7_3.avro
  tests/data/sample_alerts/lsst/lsst.v7_4.avro
  tests/load_data.py
  tests/test_alert.py
  tests/test_registry.py
Labels: enhancement
